First approach for the join structure problem
brunocalou/NaiveDB pull request #2
Opened 2016-10-24 05:09 UTC by handre

#1 
Nesse commit criei o método naiveJoin, que faz o inner join de duas tabelas varrendo elas inteiras.

2016-10-24 18:06 UTC, brunocalou requested changes
Adicionei alguns comentários sobre a implementação

2016-10-24 18:06 UTC, brunocalou commented on main.cpp
> +    vector<vector<long long>>* joinResult = person_table.naiveJoin("_id", worked_table, "person_id");
No projeto, o nome de variáveis é escrito em kebab case (kebab_case_name) enquanto que o de funções, em camel case (camelCaseName)

2016-10-24 18:06 UTC, brunocalou commented on main.cpp
> +    	for(int personCollumn=0; personCollumn <person_table.getSchema().getCols()->size(); personCollumn++){
column *
seria person_column

2016-10-24 18:06 UTC, brunocalou commented on main.cpp
> +    	for(int workedCollumn=0; workedCollumn <worked_table.getSchema().getCols()->size(); workedCollumn++){
worked_column

2016-10-24 18:06 UTC, brunocalou commented on schema.h
> +    throw std::invalid_argument( "There is no collumn with the name \""+key+"\" in this Schema");
Aqui seria legal retornar um número inválido, como -1, ao invés de lançar uma exceção, por que se não toda vez que o método for chamado, será necessário usar try catch.
Define um enum SchemaErrors contendo INVALID_NAME = -1 no início do arquivo e retorna ele nesse método

2016-10-24 18:06 UTC, brunocalou commented on schema.h
> +    return &cols.at(getColPosition(key));
depois de alterar o método getColPosition, altera esse para retornar null se a chave não for encontrada
int pos = getColPosition(key);
if (pos == INVALID_NAME) return null;

2016-10-24 18:06 UTC, brunocalou commented on table.h
> +vector<vector<long long>>* Table::naiveJoin(string thisCollumnName, Table otherTable, string otherCollumnName) {
vector<vector<long long>>\* Table::naiveJoin(string this_column_name, Table other_table, string other_column_name) {

2016-10-24 18:06 UTC, brunocalou commented on table.h
> +    int thisCollumnPosition = schema.getColPosition(thisCollumnName);
this_column_position

2016-10-24 18:06 UTC, brunocalou commented on table.h
> +    int otherCollumnPosition = otherTable.schema.getColPosition(otherCollumnName);
other_column_position

2016-10-24 18:06 UTC, brunocalou commented on table.h
> +        vector<string> thisRow = getRow(header->at(counter).second);
this_row

2016-10-24 18:06 UTC, brunocalou commented on table.h
> +            vector<string> otherRow = otherTable.getRow(otherTable.header->at(i).second);
other_row

2016-10-24 18:06 UTC, brunocalou commented on table.h
> +                vector<long long> joinRow;
join_row

2016-10-24 18:06 UTC, brunocalou commented on table.h
> +                //For debugging purpouse, cout << "insterted "<< header->at(counter).second<< " and " << otherTable.header->at(i).second << endl;
purpose *

2016-10-24 18:06 UTC, brunocalou commented on table.h
> +        // for eache Row in this table, search for all matches in the other table
each *

2016-10-24 18:06 UTC, brunocalou commented on table.h
> +     *Perform a simple inner join using the tables choosed collumns
Adiciona na documentação que depois de usar o resultado, a memória deve ser desalocada, pois o método precisou alocar usando o operador new

2016-10-24 18:06 UTC, brunocalou commented on main.cpp
> +
precisa liberar o recurso alocado pelo método naiveJoin
delete join_result;
join_result = null;

2016-10-24 18:11 UTC, handre commented on schema.h
> +    throw std::invalid_argument( "There is no collumn with the name \""+key+"\" in this Schema");
essa necessidade de try catch não é só no Java?
eu pude usar esse método sem colocar dentro de um try...

2016-10-24 18:12 UTC, handre commented on table.h
> +     *Perform a simple inner join using the tables choosed collumns
por isso que tava dando crash do final =/ não tava entendendo

2016-10-24 18:37 UTC, brunocalou commented on schema.h
> +    throw std::invalid_argument( "There is no collumn with the name \""+key+"\" in this Schema");
Não é necessário, como dá pra retornar um número que indique erro, fica fácil de verificar. Os outros métodos do projeto também não estão lançando exceções, então é melhor manter o padrão
int pos = table.getColPosition(...);
if (pos >= 0) {
    // deu certo
}

2016-10-26 13:49 UTC, brunocalou approved these changes

2016-10-26 20:21 UTC, merged